Corrige erros de digitação
pythonfluente/pythonfluente2e pull request #60
Opened 2023-09-02 15:02 UTC by jairhenrique

@ramalho dessa vez eu abri um pr com a correção de vários capítulos. Me diga se prefere assim ou um capítulo por PR.

2023-09-05 18:16 UTC, ramalho requested changes

2023-09-05 18:16 UTC, ramalho commented on capitulos/cap16.adoc
O erro não foi a falta de acento em "incluído", e sim a falta de um "n": o correto seria "incluindo".

2023-09-05 18:16 UTC, ramalho commented on capitulos/cap17.adoc
> +atributos de instância ou classe não são necessários para manter o contexto
A palavra certa nesse contexto é "clausura". O trecho ficará melhor se você editar assim: "atributos de instância ou uma clausura não são necessários...". Acrescentei "uma".

2023-09-05 18:17 UTC, ramalho commented
> @ramalho dessa vez eu abri um pr com a correção de vários capítulos. Me diga se prefere assim ou um capítulo por PR.

Pode ser assim, um PR com correções em vários arquivos. Daí fazemos esse processo de revisão, OK?

2023-09-05 18:23 UTC, jairhenrique commented on capitulos/cap16.adoc
Fiz um "replace all" e não me atentei ao contexto. Corrigido.

2023-09-12 03:03 UTC, ramalho approved these changes
👍

2023-09-12 03:03 UTC, merged

2023-09-12 03:04 UTC, ramalho commented
Muito grato pelas suas contribuições, @jairhenrique !